version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - backend/.env
    environment:
      - DATABASE_URL=postgresql://launchuser:launchpass@db:5432/launchpage
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - backend_data:/app/data
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - backend
  
  db:
    image: postgres:14
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_USER=launchuser
      - POSTGRES_PASSWORD=launchpass
      - POSTGRES_DB=launchpage
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  backend_data:
  postgres_data:
