version: '3.8'

services:
  launchpage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - launchpage_data:/app/data

volumes:
  launchpage_data:
